import next from "next";
import Head from 'next/head'
import SideNav from "../../components/SideNav/SideNav";
import HeaderNav from "../../components/HeaderNav/HeaderNav";
import CardBlock from "../../components/CardBlock/CardBlock";
import React, {useState} from "react";
import { ApiService } from "../../services/api.service";

export default function Home(props:any) {

  // const [customerList, setCustomerList] = useState(props.res);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <main>
          <div className={`d-flex`}>
              <SideNav/>
              <div className={`RightPanel`}>
                  <HeaderNav/>
                  <CardBlock customerList={props.res.data}/>
              </div>
          </div>
      </main>
    </>
  )
}
export async function getServerSideProps() {

  const baseUrl = new ApiService();
  const response = await fetch(baseUrl.getBaseUrl() + `/get-customer-data`);
  const res = await response.json();

   return { props: {res}}

}
