import Head from 'next/head'
import SideNav from "../../components/SideNav/SideNav";
import HeaderNav from "../../components/HeaderNav/HeaderNav";
import CardBlock from "../../components/CardBlock/CardBlock";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className={`d-flex`}>
              <SideNav/>
              <div className={`RightPanel`}>
                  <HeaderNav/>
                  <CardBlock/>
              </div>
          </div>
      </main>
    </>
  )
}
